# -*-coding:utf-8-*-
# Linda Tian  Oct 2021
# Email TLS encryptin by python module
# This module 4 arguments:
# recipient, subject, email_contents,filename

import smtplib
import email
from os.path import basename
from email import encoders
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from email.utils import COMMASPACE, formatdate

recipient_list = []
subject = ''
filename = ''
email_contents = ''

def mod_email_tls(recipient, subject, email_contents, filename):
    sender = 'notification.naas@telus.com'
    recipient = recipient
    subject = subject

    Text = 'This is an automated email generated by production tool server script. The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future. '
    Text = Text + '\n\n' + email_contents

    msg = MIMEMultipart()
    msg['From'] = sender
    msg['To'] = recipient
    msg['Subject'] = subject
    msg['Date'] = formatdate(localtime=True)

    msg.attach(MIMEText(Text))

    with open(filename, "rb") as fil:
        part = MIMEApplication(
            fil.read(),
            Name=basename(filename)
            )

    part['Content-Disposition'] = 'attachment; filename="%s"' % basename(filename)
    msg.attach(part)
    mail=smtplib.SMTP('96.1.254.150', 25)
    mail.starttls()

    mail.sendmail(sender,recipient,msg.as_string())
    mail.close

def main():
    recipient_list = ['vitor.lopesdemoura@telus.com','telus.sdn.dev.reg@gmail.com']
    # Note we need to loop for every single email address which defined in recipient_list
    subject = 'Remedy Alarm Automation Data Collection'
    filename = 'remedy-alarm-automation-data.csv'
    email_contents = 'Email module updated under C:\python-script\email-test\module_email_smtpTLS.py'

    for recp in recipient_list:
        mod_email_tls(recp, subject, email_contents, filename)
    print ('Task completed!')

if __name__ == '__main__':
    main()
